name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: bug
body:
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. Scroll down to '....'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Actual Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Screenshort
    description: If applicable, add screenshots to help explain your problem.
    placeholder: Ctr + V to paste your screenshot here, or use ![alt](url) for an url image
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment (Optional)
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Context (Optional)
    description: Any Context ?
    placeholder: Add any other context about the problem here.
  validations:
    required: false
