name: Chore
description: Setup repository
title: "Chore: <short_description>"
labels: chore
body:
- type: textarea
  attributes:
    label: Modified Part
    description: Which part will be modified ?
  validations:
    required: false
- type: textarea
  attributes:
    label: Description
    description: A clear and concise description of the changes.
  validations:
    required: false
