name: Feature request
description: Request for a new feature
title: "Feature: <title>"
labels: enhancement
body:
- type: textarea
  attributes:
    label: Context
    description: A clear and concise description of why we need a new feature.
  validations:
    required: false
- type: textarea
  attributes:
    label: Solution
    description: A clear and concise description of what you want to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Requirement
    description: A clear and concise description of how can we do that.
  validations:
    required: false
